// export const countries: string[] = [
//   'Австрия',
//   'Австралия',
//   'Азербайджан',
//   'Албания',
//   'Алжир',
//   'Ангола',
//   'Андорра',
//   'Антигуа и Барбуда',
//   'Аргентина',
//   'Армения',
//   'Афганистан',
//   'Багамы',
//   'Бангладеш',
//   'Барбадос',
//   'Бахрейн',
//   'Белоруссия',
//   'Белиз',
//   'Бельгия',
//   'Бенин',
//   'Болгария',
//   'Боливия',
//   'Босния и Герцеговина',
//   'Ботсвана',
//   'Бразилия',
//   'Бруней',
//   'Буркина-Фасо',
//   'Бурунди',
//   'Бутан',
//   'Вануату',
//   'Великобритания',
//   'Венгрия',
//   'Венесуэла',
//   'Восточный Тимор',
//   'Вьетнам',
//   'Габон',
//   'Гаити',
//   'Гайана',
//   'Гамбия',
//   'Гана',
//   'Гватемала',
//   'Гвинея',
//   'Гвинея-Бисау',
//   'Германия',
//   'Гондурас',
//   'Гренада',
//   'Греция',
//   'Грузия',
//   'Дания',
//   'Джибути',
//   'Доминика',
//   'Доминикана',
//   'Египет',
//   'Замбия',
//   'Зимбабве',
//   'Израиль',
//   'Индия',
//   'Индонезия',
//   'Иордания',
//   'Ирак',
//   'Иран',
//   'Ирландия',
//   'Исландия',
//   'Испания',
//   'Италия',
//   'Йемен',
//   'Кабо-Верде',
//   'Казахстан',
//   'Камбоджа',
//   'Камерун',
//   'Канада',
//   'Катар',
//   'Кения',
//   'Кипр',
//   'Киргизия',
//   'Кирибати',
//   'Китай',
//   'Колумбия',
//   'Коморы',
//   'Конго',
//   'ДР Конго',
//   'КНДР',
//   'Корея',
//   'Коста-Рика',
//   'Кот-д’Ивуар',
//   'Куба',
//   'Кувейт',
//   'Лаос',
//   'Латвия',
//   'Лесото',
//   'Либерия',
//   'Ливан',
//   'Ливия',
//   'Литва',
//   'Лихтенштейн',
//   'Люксембург',
//   'Маврикий',
//   'Мавритания',
//   'Мадагаскар',
//   'Малави',
//   'Малайзия',
//   'Мали',
//   'Мальдивы',
//   'Мальта',
//   'Марокко',
//   'Маршалловы Острова',
//   'Мексика',
//   'Микронезия',
//   'Мозамбик',
//   'Молдавия',
//   'Монако',
//   'Монголия',
//   'Мьянма',
//   'Намибия',
//   'Науру',
//   'Непал',
//   'Нигер',
//   'Нигерия',
//   'Нидерланды',
//   'Никарагуа',
//   'Новая Зеландия',
//   'Норвегия',
//   'ОАЭ',
//   'Оман',
//   'Пакистан',
//   'Палау',
//   'Панама',
//   'Папуа — Новая Гвинея',
//   'Парагвай',
//   'Перу',
//   'Польша',
//   'Португалия',
//   'Россия',
//   'Руанда',
//   'Румыния',
//   'Сальвадор',
//   'Самоа',
//   'Сан-Марино',
//   'Сан-Томе и Принсипи',
//   'Саудовская Аравия',
//   'Северная Македония',
//   'Сейшелы',
//   'Сенегал',
//   'Сент-Винсент и Гренадины',
//   'Сент-Китс и Невис',
//   'Сент-Люсия',
//   'Сербия',
//   'Сингапур',
//   'Сирия',
//   'Словакия',
//   'Словения',
//   'США',
//   'Соломоновы Острова',
//   'Сомали',
//   'Судан',
//   'Суринам',
//   'Сьерра-Леоне',
//   'Таджикистан',
//   'Таиланд',
//   'Танзания',
//   'Того',
//   'Тонга',
//   'Тринидад и Тобаго',
//   'Тувалу',
//   'Тунис',
//   'Туркменистан',
//   'Турция',
//   'Уганда',
//   'Узбекистан',
//   'Украина',
//   'Уругвай',
//   'Фиджи',
//   'Филиппины',
//   'Финляндия',
//   'Франция',
//   'Хорватия',
//   'ЦАР',
//   'Чад',
//   'Черногория',
//   'Чехия',
//   'Чили',
//   'Швейцария',
//   'Швеция',
//   'Шри-Ланка',
//   'Эквадор',
//   'Экваториальная Гвинея',
//   'Эритрея',
//   'Эсватини',
//   'Эстония',
//   'Эфиопия',
//   'ЮАР',
//   'Южный Судан',
//   'Ямайка',
//   'Япония'
// ];

export const countries: string[] = [ 
  'Afghanistan',
  'Åland Islands',
  'Albania',
  'Algeria',
  'American Samoa',
  'AndorrA',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo',
  'Cook Islands',
  'Costa Rica',
  'Cote D\'Ivoire',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and Mcdonald Islands',
  'Holy See (Vatican City State)',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'North Korea',
  'South Korea',
  'Kuwait',
  'Kyrgyzstan',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libyan Arab Jamahiriya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestinian Territory',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reunion',
  'Romania',
  'Russian Federation',
  'RWANDA',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia and Montenegro',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Viet Nam',
  'Virgin Islands',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe'
]
